### ISSUE TITLE
Improve queries for Juniper

### ISSUE THREAD

**Issue by dnkolegov** [sdnewhop/sdwannewhope#2]
Queries are finding all Juniper products. Improve.

**Comment by manmolecular** [comment]
I've tried a lot of different queries, but all of them can't find exactly what we need - [Contrail Service Orchestration(CSO)](https://www.youtube.com/watch?v=sLpOYrg8Nks) product from Juniper.

I tried to update the filters to avoid some of wrong results from current queries:
1. Filtering by products that not compatible based on favicon hash:
`http.favicon.hash:2141724739 -title:"VPN" -title:"API" -title:"Web Device Manager" -title:"Networks Web Management" -title:"Firewall"` (42 results)
1. Based on "Juniper Networks" string:
`"Juniper Networks" -title:"VPN" -title:"API" -title:"Web Device Manager" -title:"Networks Web Management" -title:"Firewall" port:"80"` (66 results)
