### ISSUE TITLE
Add Censys queries for Citrix SD-WAN and SD-WAN Center

### ISSUE THREAD

**Issue by dnkolegov** [sdnewhop/sdwannewhope#5]

**Comment by manmolecular** [comment]
Thanks, i will fix all Censys queries in my [branch](https://github.com/sdnewhop/sdwannewhope/tree/census-update), because many Shodan queries were changed.

**Comment by manmolecular** [comment]
New Censys queries for Citrix:
1. Search NetScaler SD-WAN Login page by certificate hash:
`443.https.tls.certificate.parsed.fingerprint_sha256:8199d53cf2832a133344559b09987b1d4830e643497f5f01d3178beb379ee7a5`
1. Search NetScaler SD-WAN Center Login page by title:
`80.http.get.title:"SD-WAN Center"`

**Comment by dnkolegov** [comment]
Fixed.
