### ISSUE TITLE
Sonus queries

### ISSUE THREAD

**Issue by manmolecular** [sdnewhop/sdwannewhope#7]
### All what we got from Sonus Networks on Shodan
Now we have some problems with Sonus SD-WAN products searching

#### Shodan results structure map:
```
All Sonus results = 408:
    - 349 - SBC:
        - 196 - SBC Edge
        - 150 - SBC 1000/2000 Web-interface
        - 3 - SBC Management Application
    - 5 - SecureLink
    - 5 - Configuration Management Unit
    - 4 - FTP Servers
    - ≈20 - Switches
    - 24 - Trash
```

#### Basic global search:
`html:Sonus` - 408 results
`http.title:"Sonus"` - 371 results
#### SSL search:
`ssl:"*.sonusnet.com"` - 244 results
`ssl:"Sonus Networks, Inc."` - 21 results

#### Directly by products:
**SBC product:** 
`html:Sonus title:"Sonus SBC"` - Sonus Session Border Controller (SBC) products, 349 results
`html:Sonus title:"SBC Management Application"` - SBC Management Application, 3 results
`html:Sonus title:"Sonus SBC Edge Web Interface"` - Sonus SBC Edge Web Interface, 195-196 results
`html:Sonus title:"SBC 1000/2000 Web Interface"` - SBC 1000/2000 Web-interface, 150 results

**SecureLink product:**
`http.favicon.hash:-1945035874` - Sonus Networks SecureLink Server, 5 results

**Configuration Management Unit:**
`http.title:"Configuration*Management*Unit"` - Sonus Configuration Management Unit, 5 results

**FTP:**
`http.favicon.hash:-318467169 -title:"Configuration"` - FTA/FTP Servers

#### Censys queries by products:
**SBC product:** 
`80.http.get.title: "SBC Management Application"` - SBC Management Application, 22 results
`80.http.get.title: "Sonus SBC Edge Web Interface"` - Sonus SBC Edge Web Interface, 156 results
`80.http.get.title: "SBC 1000/2000 Web Interface"` -  SBC 1000/2000 Web-interface, 99 results

**SecureLink product:**
`80.http.get.title: "Sonus Networks SecureLink Server"` - Sonus Networks SecureLink Server, 3 results

**Configuration Management Unit:**
`80.http.get.title: "Configuration Management Unit"` - Sonus Configuration Management Unit, 6 results

**Comment by manmolecular** [comment]
Update queries.

**Comment by dnkolegov** [comment]
Fixed via https://github.com/sdnewhop/sdwannewhope/pull/8
